using System;
using System.Collections.Generic;
using System.Globalization;

namespace SesliOkuma
{
    // UI localization. Keys are looked up in the active language, then English, then returned raw.
    public static class L
    {
        public static readonly string[] Languages = { "tr", "en", "zh", "hi", "es", "fr", "ar", "pt" };
        public static string Lang = "tr";

        public static bool IsRtl { get { return Lang == "ar"; } }

        public static string NativeName(string code)
        {
            switch (code)
            {
                case "tr": return "Türkçe";
                case "en": return "English";
                case "zh": return "中文";
                case "hi": return "हिन्दी";
                case "es": return "Español";
                case "fr": return "Français";
                case "ar": return "العربية";
                case "pt": return "Português";
            }
            return code;
        }

        public static string DetectSystemLanguage()
        {
            string two = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
            foreach (string l in Languages) if (l == two) return l;
            return "en";
        }

        public static string T(string key)
        {
            Dictionary<string, string> d;
            string s;
            if (D.TryGetValue(Lang, out d) && d.TryGetValue(key, out s)) return s;
            if (D.TryGetValue("en", out d) && d.TryGetValue(key, out s)) return s;
            return key;
        }

        public static string F(string key, params object[] args) { return string.Format(T(key), args); }

        // Sample sentence spoken when previewing a voice, keyed by the voice's language.
        public static string Sample(string lang2, string voiceName)
        {
            switch (lang2)
            {
                case "tr": return "Merhaba, ben " + voiceName + ". Seçtiğiniz metinleri bu sesle okuyacağım.";
                case "zh": return "你好，我是" + voiceName + "。我将用这个声音朗读您选择的文字。";
                case "hi": return "नमस्ते, मैं " + voiceName + " हूँ। मैं आपके चुने हुए पाठ को इस आवाज़ में पढ़ूँगा।";
                case "es": return "Hola, soy " + voiceName + ". Leeré el texto que selecciones con esta voz.";
                case "fr": return "Bonjour, je suis " + voiceName + ". Je lirai le texte sélectionné avec cette voix.";
                case "ar": return "مرحباً، أنا " + voiceName + ". سأقرأ النص الذي تحدده بهذا الصوت.";
                case "pt": return "Olá, eu sou " + voiceName + ". Vou ler o texto selecionado com esta voz.";
                case "de": return "Hallo, ich bin " + voiceName + ". Ich lese den markierten Text mit dieser Stimme.";
                case "ru": return "Здравствуйте, я " + voiceName + ". Я прочитаю выделенный текст этим голосом.";
                case "ja": return "こんにちは、" + voiceName + "です。選択したテキストをこの声で読み上げます。";
                case "ko": return "안녕하세요, 저는 " + voiceName + "입니다. 선택한 텍스트를 이 목소리로 읽어 드리겠습니다.";
                case "it": return "Ciao, sono " + voiceName + ". Leggerò il testo selezionato con questa voce.";
            }
            return "Hi, I'm " + voiceName + ". I will read your selected text with this voice.";
        }

        static readonly Dictionary<string, Dictionary<string, string>> D = Build();

        static Dictionary<string, Dictionary<string, string>> Build()
        {
            var all = new Dictionary<string, Dictionary<string, string>>();

            all["tr"] = new Dictionary<string, string> {
                {"Subtitle", "{0}  seçili metni okur  ·  tekrar basınca susar"},
                {"Hotkey", "KISAYOL"},
                {"HotkeyHint", "Değiştirmek için tıklayın"},
                {"HotkeyCapture", "Yeni tuş kombinasyonuna basın…  (Esc iptal)"},
                {"HotkeyNeedMod", "Ctrl, Alt, Shift veya Win ile birlikte bir tuş seçin"},
                {"HotkeyTaken", "{0} başka bir uygulama tarafından kullanılıyor"},
                {"HotkeySaved", "Kısayol: {0}"},
                {"Primary", "ANA DİL"},
                {"Other", "DİĞER DİLLER"},
                {"NoVoice", "Ses seçilmedi"},
                {"PickVoice", "Tıklayıp bir ses seçin"},
                {"Natural", "doğal ses"},
                {"Classic", "klasik ses"},
                {"Multilingual", "çok dilli"},
                {"Speed", "OKUMA HIZI"},
                {"Normal", "Normal"},
                {"Fast", "Hızlı"},
                {"Slow", "Yavaş"},
                {"StartWithWindows", "Windows ile başlat"},
                {"AutoUpdate", "Güncellemeleri otomatik denetle"},
                {"Language", "Arayüz dili"},
                {"Check", "denetle"},
                {"Checking", "Güncelleme denetleniyor…"},
                {"UpToDate", "Güncel: {0}"},
                {"CheckFailed", "Güncelleme denetlenemedi (ağ?)"},
                {"NewVersion", "Yeni sürüm {0} hazır"},
                {"ReleaseNotes", "Sürüm notları için tıklayın"},
                {"Update", "Güncelle"},
                {"Skipped", "Bu sürüm atlandı"},
                {"Downloading", "İndiriliyor…  %{0}"},
                {"Installing", "Doğrulanıyor ve kuruluyor…"},
                {"RestartSoon", "Uygulama birkaç saniye içinde yeniden başlayacak"},
                {"UpdateClick", "Güncellemek için tıklayın."},
                {"NaturalTitle", "Doğal, insan gibi sesler"},
                {"NaturalText", "Emel ve Ahmet dahil neural sesleri ücretsiz ekleyin"},
                {"Install", "Kur"},
                {"NaturalInstalling", "Doğal sesler kuruluyor…  %{0}"},
                {"NaturalRegistering", "Sesler sisteme kaydediliyor (yönetici onayı)…"},
                {"NaturalDone", "Doğal sesler eklendi"},
                {"NaturalFailed", "Kurulum tamamlanamadı: {0}"},
                {"NaturalNote", "Açık kaynak NaturalVoiceSAPIAdapter · Microsoft çevrimiçi sesleri · internet gerekir"},
                {"MoreVoices", "Windows ses paketleri ekle…"},
                {"Settings", "Ayarlar"},
                {"Stop", "Sustur"},
                {"CheckUpdates", "Güncellemeleri denetle"},
                {"Exit", "Çıkış"},
                {"VoiceSelected", "{0} seçildi"},
                {"StartupAdded", "Başlangıca eklendi"},
                {"StartupRemoved", "Başlangıçtan kaldırıldı"},
                {"HotkeyFailBalloon", "{0} kaydedilemedi (başka uygulama kullanıyor)"},
                {"TrayTip", "Sesli Okuma  ·  {0}"},
                {"Ready", "Sesli Okuma {0} hazır"},
                {"Cancelled", "İptal edildi"},
            };

            all["en"] = new Dictionary<string, string> {
                {"Subtitle", "{0}  reads the selected text  ·  press again to stop"},
                {"Hotkey", "SHORTCUT"},
                {"HotkeyHint", "Click to change"},
                {"HotkeyCapture", "Press the new key combination…  (Esc to cancel)"},
                {"HotkeyNeedMod", "Combine a key with Ctrl, Alt, Shift or Win"},
                {"HotkeyTaken", "{0} is already used by another application"},
                {"HotkeySaved", "Shortcut: {0}"},
                {"Primary", "PRIMARY LANGUAGE"},
                {"Other", "OTHER LANGUAGES"},
                {"NoVoice", "No voice selected"},
                {"PickVoice", "Click to choose a voice"},
                {"Natural", "natural voice"},
                {"Classic", "classic voice"},
                {"Multilingual", "multilingual"},
                {"Speed", "READING SPEED"},
                {"Normal", "Normal"},
                {"Fast", "Fast"},
                {"Slow", "Slow"},
                {"StartWithWindows", "Start with Windows"},
                {"AutoUpdate", "Check for updates automatically"},
                {"Language", "Interface language"},
                {"Check", "check"},
                {"Checking", "Checking for updates…"},
                {"UpToDate", "Up to date: {0}"},
                {"CheckFailed", "Update check failed (network?)"},
                {"NewVersion", "Version {0} is available"},
                {"ReleaseNotes", "Click for release notes"},
                {"Update", "Update"},
                {"Skipped", "This version was skipped"},
                {"Downloading", "Downloading…  {0}%"},
                {"Installing", "Verifying and installing…"},
                {"RestartSoon", "The app will restart in a few seconds"},
                {"UpdateClick", "Click to update."},
                {"NaturalTitle", "Natural, human-like voices"},
                {"NaturalText", "Add free neural voices for many languages"},
                {"Install", "Install"},
                {"NaturalInstalling", "Installing natural voices…  {0}%"},
                {"NaturalRegistering", "Registering voices (administrator approval)…"},
                {"NaturalDone", "Natural voices added"},
                {"NaturalFailed", "Installation did not complete: {0}"},
                {"NaturalNote", "Open-source NaturalVoiceSAPIAdapter · Microsoft online voices · requires internet"},
                {"MoreVoices", "Add Windows voice packs…"},
                {"Settings", "Settings"},
                {"Stop", "Stop"},
                {"CheckUpdates", "Check for updates"},
                {"Exit", "Exit"},
                {"VoiceSelected", "{0} selected"},
                {"StartupAdded", "Added to startup"},
                {"StartupRemoved", "Removed from startup"},
                {"HotkeyFailBalloon", "Could not register {0} (used by another app)"},
                {"TrayTip", "Sesli Okuma  ·  {0}"},
                {"Ready", "Sesli Okuma {0} is ready"},
                {"Cancelled", "Cancelled"},
            };

            all["zh"] = new Dictionary<string, string> {
                {"Subtitle", "{0}  朗读选中的文字  ·  再按一次停止"},
                {"Hotkey", "快捷键"},
                {"HotkeyHint", "点击更改"},
                {"HotkeyCapture", "请按下新的组合键…  (Esc 取消)"},
                {"HotkeyNeedMod", "请与 Ctrl、Alt、Shift 或 Win 组合使用"},
                {"HotkeyTaken", "{0} 已被其他应用占用"},
                {"HotkeySaved", "快捷键：{0}"},
                {"Primary", "主要语言"},
                {"Other", "其他语言"},
                {"NoVoice", "未选择语音"},
                {"PickVoice", "点击选择语音"},
                {"Natural", "自然语音"},
                {"Classic", "经典语音"},
                {"Multilingual", "多语言"},
                {"Speed", "朗读速度"},
                {"Normal", "正常"},
                {"Fast", "快"},
                {"Slow", "慢"},
                {"StartWithWindows", "随 Windows 启动"},
                {"AutoUpdate", "自动检查更新"},
                {"Language", "界面语言"},
                {"Check", "检查"},
                {"Checking", "正在检查更新…"},
                {"UpToDate", "已是最新：{0}"},
                {"CheckFailed", "无法检查更新（网络？）"},
                {"NewVersion", "新版本 {0} 可用"},
                {"ReleaseNotes", "点击查看更新说明"},
                {"Update", "更新"},
                {"Skipped", "已跳过此版本"},
                {"Downloading", "正在下载…  {0}%"},
                {"Installing", "正在验证并安装…"},
                {"RestartSoon", "应用将在几秒后重新启动"},
                {"UpdateClick", "点击更新。"},
                {"NaturalTitle", "自然、拟人的语音"},
                {"NaturalText", "免费添加多种语言的神经网络语音"},
                {"Install", "安装"},
                {"NaturalInstalling", "正在安装自然语音…  {0}%"},
                {"NaturalRegistering", "正在注册语音（需要管理员确认）…"},
                {"NaturalDone", "已添加自然语音"},
                {"NaturalFailed", "安装未完成：{0}"},
                {"NaturalNote", "开源 NaturalVoiceSAPIAdapter · Microsoft 在线语音 · 需要网络"},
                {"MoreVoices", "添加 Windows 语音包…"},
                {"Settings", "设置"},
                {"Stop", "停止"},
                {"CheckUpdates", "检查更新"},
                {"Exit", "退出"},
                {"VoiceSelected", "已选择 {0}"},
                {"StartupAdded", "已添加到启动项"},
                {"StartupRemoved", "已从启动项移除"},
                {"HotkeyFailBalloon", "无法注册 {0}（被其他应用占用）"},
                {"TrayTip", "Sesli Okuma  ·  {0}"},
                {"Ready", "Sesli Okuma {0} 已就绪"},
                {"Cancelled", "已取消"},
            };

            all["hi"] = new Dictionary<string, string> {
                {"Subtitle", "{0}  चयनित पाठ पढ़ता है  ·  रोकने के लिए फिर दबाएँ"},
                {"Hotkey", "शॉर्टकट"},
                {"HotkeyHint", "बदलने के लिए क्लिक करें"},
                {"HotkeyCapture", "नई कुंजी संयोजन दबाएँ…  (रद्द करने के लिए Esc)"},
                {"HotkeyNeedMod", "किसी कुंजी को Ctrl, Alt, Shift या Win के साथ मिलाएँ"},
                {"HotkeyTaken", "{0} पहले से किसी अन्य ऐप द्वारा उपयोग में है"},
                {"HotkeySaved", "शॉर्टकट: {0}"},
                {"Primary", "मुख्य भाषा"},
                {"Other", "अन्य भाषाएँ"},
                {"NoVoice", "कोई आवाज़ चयनित नहीं"},
                {"PickVoice", "आवाज़ चुनने के लिए क्लिक करें"},
                {"Natural", "प्राकृतिक आवाज़"},
                {"Classic", "क्लासिक आवाज़"},
                {"Multilingual", "बहुभाषी"},
                {"Speed", "पढ़ने की गति"},
                {"Normal", "सामान्य"},
                {"Fast", "तेज़"},
                {"Slow", "धीमा"},
                {"StartWithWindows", "Windows के साथ शुरू करें"},
                {"AutoUpdate", "अपडेट स्वतः जाँचें"},
                {"Language", "इंटरफ़ेस भाषा"},
                {"Check", "जाँचें"},
                {"Checking", "अपडेट जाँचे जा रहे हैं…"},
                {"UpToDate", "नवीनतम: {0}"},
                {"CheckFailed", "अपडेट जाँच विफल (नेटवर्क?)"},
                {"NewVersion", "संस्करण {0} उपलब्ध है"},
                {"ReleaseNotes", "रिलीज़ नोट्स के लिए क्लिक करें"},
                {"Update", "अपडेट"},
                {"Skipped", "यह संस्करण छोड़ दिया गया"},
                {"Downloading", "डाउनलोड हो रहा है…  {0}%"},
                {"Installing", "सत्यापन और इंस्टॉल हो रहा है…"},
                {"RestartSoon", "ऐप कुछ सेकंड में पुनः प्रारंभ होगा"},
                {"UpdateClick", "अपडेट करने के लिए क्लिक करें।"},
                {"NaturalTitle", "प्राकृतिक, मानव-जैसी आवाज़ें"},
                {"NaturalText", "कई भाषाओं के लिए मुफ़्त न्यूरल आवाज़ें जोड़ें"},
                {"Install", "इंस्टॉल"},
                {"NaturalInstalling", "प्राकृतिक आवाज़ें इंस्टॉल हो रही हैं…  {0}%"},
                {"NaturalRegistering", "आवाज़ें पंजीकृत हो रही हैं (प्रशासक अनुमति)…"},
                {"NaturalDone", "प्राकृतिक आवाज़ें जोड़ी गईं"},
                {"NaturalFailed", "इंस्टॉल पूरा नहीं हुआ: {0}"},
                {"NaturalNote", "ओपन-सोर्स NaturalVoiceSAPIAdapter · Microsoft ऑनलाइन आवाज़ें · इंटरनेट आवश्यक"},
                {"MoreVoices", "Windows आवाज़ पैक जोड़ें…"},
                {"Settings", "सेटिंग्स"},
                {"Stop", "रोकें"},
                {"CheckUpdates", "अपडेट जाँचें"},
                {"Exit", "बाहर निकलें"},
                {"VoiceSelected", "{0} चयनित"},
                {"StartupAdded", "स्टार्टअप में जोड़ा गया"},
                {"StartupRemoved", "स्टार्टअप से हटाया गया"},
                {"HotkeyFailBalloon", "{0} पंजीकृत नहीं हो सका (अन्य ऐप द्वारा उपयोग में)"},
                {"TrayTip", "Sesli Okuma  ·  {0}"},
                {"Ready", "Sesli Okuma {0} तैयार है"},
                {"Cancelled", "रद्द किया गया"},
            };

            all["es"] = new Dictionary<string, string> {
                {"Subtitle", "{0}  lee el texto seleccionado  ·  pulsa otra vez para detener"},
                {"Hotkey", "ATAJO"},
                {"HotkeyHint", "Haz clic para cambiar"},
                {"HotkeyCapture", "Pulsa la nueva combinación de teclas…  (Esc cancela)"},
                {"HotkeyNeedMod", "Combina una tecla con Ctrl, Alt, Mayús o Win"},
                {"HotkeyTaken", "{0} ya lo usa otra aplicación"},
                {"HotkeySaved", "Atajo: {0}"},
                {"Primary", "IDIOMA PRINCIPAL"},
                {"Other", "OTROS IDIOMAS"},
                {"NoVoice", "Ninguna voz seleccionada"},
                {"PickVoice", "Haz clic para elegir una voz"},
                {"Natural", "voz natural"},
                {"Classic", "voz clásica"},
                {"Multilingual", "multilingüe"},
                {"Speed", "VELOCIDAD DE LECTURA"},
                {"Normal", "Normal"},
                {"Fast", "Rápido"},
                {"Slow", "Lento"},
                {"StartWithWindows", "Iniciar con Windows"},
                {"AutoUpdate", "Buscar actualizaciones automáticamente"},
                {"Language", "Idioma de la interfaz"},
                {"Check", "comprobar"},
                {"Checking", "Buscando actualizaciones…"},
                {"UpToDate", "Actualizado: {0}"},
                {"CheckFailed", "No se pudo comprobar (¿red?)"},
                {"NewVersion", "Versión {0} disponible"},
                {"ReleaseNotes", "Haz clic para ver las novedades"},
                {"Update", "Actualizar"},
                {"Skipped", "Versión omitida"},
                {"Downloading", "Descargando…  {0}%"},
                {"Installing", "Verificando e instalando…"},
                {"RestartSoon", "La aplicación se reiniciará en unos segundos"},
                {"UpdateClick", "Haz clic para actualizar."},
                {"NaturalTitle", "Voces naturales, casi humanas"},
                {"NaturalText", "Añade voces neuronales gratuitas para muchos idiomas"},
                {"Install", "Instalar"},
                {"NaturalInstalling", "Instalando voces naturales…  {0}%"},
                {"NaturalRegistering", "Registrando voces (permiso de administrador)…"},
                {"NaturalDone", "Voces naturales añadidas"},
                {"NaturalFailed", "La instalación no se completó: {0}"},
                {"NaturalNote", "NaturalVoiceSAPIAdapter de código abierto · voces en línea de Microsoft · requiere internet"},
                {"MoreVoices", "Añadir paquetes de voz de Windows…"},
                {"Settings", "Ajustes"},
                {"Stop", "Detener"},
                {"CheckUpdates", "Buscar actualizaciones"},
                {"Exit", "Salir"},
                {"VoiceSelected", "{0} seleccionada"},
                {"StartupAdded", "Añadido al inicio"},
                {"StartupRemoved", "Quitado del inicio"},
                {"HotkeyFailBalloon", "No se pudo registrar {0} (lo usa otra app)"},
                {"TrayTip", "Sesli Okuma  ·  {0}"},
                {"Ready", "Sesli Okuma {0} está listo"},
                {"Cancelled", "Cancelado"},
            };

            all["fr"] = new Dictionary<string, string> {
                {"Subtitle", "{0}  lit le texte sélectionné  ·  appuyez à nouveau pour arrêter"},
                {"Hotkey", "RACCOURCI"},
                {"HotkeyHint", "Cliquez pour modifier"},
                {"HotkeyCapture", "Appuyez sur la nouvelle combinaison…  (Échap pour annuler)"},
                {"HotkeyNeedMod", "Combinez une touche avec Ctrl, Alt, Maj ou Win"},
                {"HotkeyTaken", "{0} est déjà utilisé par une autre application"},
                {"HotkeySaved", "Raccourci : {0}"},
                {"Primary", "LANGUE PRINCIPALE"},
                {"Other", "AUTRES LANGUES"},
                {"NoVoice", "Aucune voix sélectionnée"},
                {"PickVoice", "Cliquez pour choisir une voix"},
                {"Natural", "voix naturelle"},
                {"Classic", "voix classique"},
                {"Multilingual", "multilingue"},
                {"Speed", "VITESSE DE LECTURE"},
                {"Normal", "Normale"},
                {"Fast", "Rapide"},
                {"Slow", "Lente"},
                {"StartWithWindows", "Démarrer avec Windows"},
                {"AutoUpdate", "Rechercher les mises à jour automatiquement"},
                {"Language", "Langue de l'interface"},
                {"Check", "vérifier"},
                {"Checking", "Recherche de mises à jour…"},
                {"UpToDate", "À jour : {0}"},
                {"CheckFailed", "Vérification impossible (réseau ?)"},
                {"NewVersion", "Version {0} disponible"},
                {"ReleaseNotes", "Cliquez pour les notes de version"},
                {"Update", "Mettre à jour"},
                {"Skipped", "Version ignorée"},
                {"Downloading", "Téléchargement…  {0}%"},
                {"Installing", "Vérification et installation…"},
                {"RestartSoon", "L'application redémarre dans quelques secondes"},
                {"UpdateClick", "Cliquez pour mettre à jour."},
                {"NaturalTitle", "Voix naturelles, presque humaines"},
                {"NaturalText", "Ajoutez gratuitement des voix neuronales pour de nombreuses langues"},
                {"Install", "Installer"},
                {"NaturalInstalling", "Installation des voix naturelles…  {0}%"},
                {"NaturalRegistering", "Enregistrement des voix (autorisation administrateur)…"},
                {"NaturalDone", "Voix naturelles ajoutées"},
                {"NaturalFailed", "Installation incomplète : {0}"},
                {"NaturalNote", "NaturalVoiceSAPIAdapter open source · voix en ligne Microsoft · connexion requise"},
                {"MoreVoices", "Ajouter des packs de voix Windows…"},
                {"Settings", "Paramètres"},
                {"Stop", "Arrêter"},
                {"CheckUpdates", "Rechercher les mises à jour"},
                {"Exit", "Quitter"},
                {"VoiceSelected", "{0} sélectionnée"},
                {"StartupAdded", "Ajouté au démarrage"},
                {"StartupRemoved", "Retiré du démarrage"},
                {"HotkeyFailBalloon", "Impossible d'enregistrer {0} (utilisé par une autre app)"},
                {"TrayTip", "Sesli Okuma  ·  {0}"},
                {"Ready", "Sesli Okuma {0} est prêt"},
                {"Cancelled", "Annulé"},
            };

            all["ar"] = new Dictionary<string, string> {
                {"Subtitle", "{0}  يقرأ النص المحدد  ·  اضغط مرة أخرى للتوقف"},
                {"Hotkey", "الاختصار"},
                {"HotkeyHint", "انقر للتغيير"},
                {"HotkeyCapture", "اضغط على مجموعة المفاتيح الجديدة…  (Esc للإلغاء)"},
                {"HotkeyNeedMod", "اجمع مفتاحاً مع Ctrl أو Alt أو Shift أو Win"},
                {"HotkeyTaken", "{0} مستخدم بالفعل في تطبيق آخر"},
                {"HotkeySaved", "الاختصار: {0}"},
                {"Primary", "اللغة الأساسية"},
                {"Other", "لغات أخرى"},
                {"NoVoice", "لم يتم اختيار صوت"},
                {"PickVoice", "انقر لاختيار صوت"},
                {"Natural", "صوت طبيعي"},
                {"Classic", "صوت كلاسيكي"},
                {"Multilingual", "متعدد اللغات"},
                {"Speed", "سرعة القراءة"},
                {"Normal", "عادية"},
                {"Fast", "سريعة"},
                {"Slow", "بطيئة"},
                {"StartWithWindows", "التشغيل مع Windows"},
                {"AutoUpdate", "التحقق من التحديثات تلقائياً"},
                {"Language", "لغة الواجهة"},
                {"Check", "تحقق"},
                {"Checking", "جارٍ التحقق من التحديثات…"},
                {"UpToDate", "محدَّث: {0}"},
                {"CheckFailed", "تعذر التحقق من التحديثات (الشبكة؟)"},
                {"NewVersion", "الإصدار {0} متاح"},
                {"ReleaseNotes", "انقر لملاحظات الإصدار"},
                {"Update", "تحديث"},
                {"Skipped", "تم تخطي هذا الإصدار"},
                {"Downloading", "جارٍ التنزيل…  {0}%"},
                {"Installing", "جارٍ التحقق والتثبيت…"},
                {"RestartSoon", "سيُعاد تشغيل التطبيق خلال ثوانٍ"},
                {"UpdateClick", "انقر للتحديث."},
                {"NaturalTitle", "أصوات طبيعية تشبه البشر"},
                {"NaturalText", "أضف أصواتاً عصبية مجانية للعديد من اللغات"},
                {"Install", "تثبيت"},
                {"NaturalInstalling", "جارٍ تثبيت الأصوات الطبيعية…  {0}%"},
                {"NaturalRegistering", "جارٍ تسجيل الأصوات (موافقة المسؤول)…"},
                {"NaturalDone", "تمت إضافة الأصوات الطبيعية"},
                {"NaturalFailed", "لم يكتمل التثبيت: {0}"},
                {"NaturalNote", "NaturalVoiceSAPIAdapter مفتوح المصدر · أصوات Microsoft عبر الإنترنت · يتطلب اتصالاً"},
                {"MoreVoices", "إضافة حزم أصوات Windows…"},
                {"Settings", "الإعدادات"},
                {"Stop", "إيقاف"},
                {"CheckUpdates", "التحقق من التحديثات"},
                {"Exit", "خروج"},
                {"VoiceSelected", "تم اختيار {0}"},
                {"StartupAdded", "تمت الإضافة إلى بدء التشغيل"},
                {"StartupRemoved", "تمت الإزالة من بدء التشغيل"},
                {"HotkeyFailBalloon", "تعذر تسجيل {0} (مستخدم في تطبيق آخر)"},
                {"TrayTip", "Sesli Okuma  ·  {0}"},
                {"Ready", "Sesli Okuma {0} جاهز"},
                {"Cancelled", "أُلغي"},
            };

            all["pt"] = new Dictionary<string, string> {
                {"Subtitle", "{0}  lê o texto selecionado  ·  pressione de novo para parar"},
                {"Hotkey", "ATALHO"},
                {"HotkeyHint", "Clique para alterar"},
                {"HotkeyCapture", "Pressione a nova combinação de teclas…  (Esc cancela)"},
                {"HotkeyNeedMod", "Combine uma tecla com Ctrl, Alt, Shift ou Win"},
                {"HotkeyTaken", "{0} já é usado por outro aplicativo"},
                {"HotkeySaved", "Atalho: {0}"},
                {"Primary", "IDIOMA PRINCIPAL"},
                {"Other", "OUTROS IDIOMAS"},
                {"NoVoice", "Nenhuma voz selecionada"},
                {"PickVoice", "Clique para escolher uma voz"},
                {"Natural", "voz natural"},
                {"Classic", "voz clássica"},
                {"Multilingual", "multilíngue"},
                {"Speed", "VELOCIDADE DE LEITURA"},
                {"Normal", "Normal"},
                {"Fast", "Rápida"},
                {"Slow", "Lenta"},
                {"StartWithWindows", "Iniciar com o Windows"},
                {"AutoUpdate", "Verificar atualizações automaticamente"},
                {"Language", "Idioma da interface"},
                {"Check", "verificar"},
                {"Checking", "Verificando atualizações…"},
                {"UpToDate", "Atualizado: {0}"},
                {"CheckFailed", "Não foi possível verificar (rede?)"},
                {"NewVersion", "Versão {0} disponível"},
                {"ReleaseNotes", "Clique para ver as novidades"},
                {"Update", "Atualizar"},
                {"Skipped", "Versão ignorada"},
                {"Downloading", "Baixando…  {0}%"},
                {"Installing", "Verificando e instalando…"},
                {"RestartSoon", "O aplicativo será reiniciado em alguns segundos"},
                {"UpdateClick", "Clique para atualizar."},
                {"NaturalTitle", "Vozes naturais, quase humanas"},
                {"NaturalText", "Adicione vozes neurais gratuitas para muitos idiomas"},
                {"Install", "Instalar"},
                {"NaturalInstalling", "Instalando vozes naturais…  {0}%"},
                {"NaturalRegistering", "Registrando vozes (permissão de administrador)…"},
                {"NaturalDone", "Vozes naturais adicionadas"},
                {"NaturalFailed", "A instalação não foi concluída: {0}"},
                {"NaturalNote", "NaturalVoiceSAPIAdapter de código aberto · vozes online da Microsoft · requer internet"},
                {"MoreVoices", "Adicionar pacotes de voz do Windows…"},
                {"Settings", "Configurações"},
                {"Stop", "Parar"},
                {"CheckUpdates", "Verificar atualizações"},
                {"Exit", "Sair"},
                {"VoiceSelected", "{0} selecionada"},
                {"StartupAdded", "Adicionado à inicialização"},
                {"StartupRemoved", "Removido da inicialização"},
                {"HotkeyFailBalloon", "Não foi possível registrar {0} (usado por outro app)"},
                {"TrayTip", "Sesli Okuma  ·  {0}"},
                {"Ready", "Sesli Okuma {0} está pronto"},
                {"Cancelled", "Cancelado"},
            };

            return all;
        }
    }
}
